### PR TITLE
feat: datadog format supported for statsd driver

### PR DESCRIPTION
**Pull request by cv65kr**
# Reason for This PR
Right now tags are combined into metric name. Since Datadog supports statsd but required different format, in result tags are allowed.
https://github.com/roadrunner-server/roadrunner/issues/1288

## Description of Changes

Add possibility to use datadog format for statsd driver - https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

**Comment by rustatian** [comment]
The leading case is not to use a specific driver (e.g. DataDog), because the only difference is a tag format, so we don't need an additional dependency.

**Comment by rustatian** [comment]
Yeah, you're right; We need to re-implement a temporal `MetricsHandler` (inject or extend this interface).

**Comment by cv65kr** [comment]
Hi @rustatian
Sorry for long time for my response. I prepared PR in tally repo to avoid creation of custom reporter - https://github.com/uber-go/tally/pull/183

After merge of that, I will update this PR 😄

**Comment by rustatian** [comment]
Nice job, @cv65kr ⚡

**Comment by rustatian** [comment]
@cv65kr Hey 👋🏻 
Looks like Uber has finally updated the `statsd` to version 5. Could you please have a look, maybe we can move forward with this PR?

**Comment by cv65kr** [comment]
Hi @rustatian version of statsd was updated, but they still not merged changes for tags supporting - https://github.com/uber-go/tally/blob/master/statsd/reporter.go#L76

**Comment by rustatian** [comment]
Yeah @cv65kr, you're right... Let's wait another year 😄

**Comment by cv65kr** [comment]
@rustatian next year let's do a party to celebrate the anniversary 🎂

**Comment by rustatian** [comment]
Sorry, but I think that Uber doesn't will to maintain their repo and merge/review PR's. Closing this PR as staled. If in the 2030 they look at the PR and review it, I would be happy to accept your new PR ❤️

**Pull request closed without merging**
